DO NOT MERGE -- prep / test Acorn
holochain/happ-index pull request #2
Opened 2019-10-29 16:44 UTC by Connoropolous

This isn't ready, I am just familiarizing with Holoscape

2020-02-13 16:07 UTC, samcooley commented on index.json
> +    "name": "Acorn Project Management",
Acorn

2020-02-13 16:11 UTC, samcooley commented on index.json
> +    "icon": null,
https://github.com/h-be/acorn-ui/blob/master/dist/logo/acorn-logo-desktop-512px%402x.png (or a smaller icon image)

2020-02-13 16:29 UTC, samcooley commented on index.json
> +    "screenshot": "...",
https://i.imgur.com/vyvdfyn.png
or 
https://i.imgur.com/2LreFT4.png

2020-02-13 16:29 UTC, samcooley commented on index.json
> +    "description": "..."
Acorn is a way of organizing intended Goals and Outcomes on a tree.  You can think of it as a virtual whiteboard for collaborative planning.

2020-02-13 16:30 UTC, samcooley requested changes
comments suggesting changes added

2020-02-25 21:52 UTC, zippy approved these changes

2020-02-26 14:43 UTC, lucksus approved these changes
:tada: :tada: :tada:

2020-02-26 14:58 UTC, merged